### ISSUE TITLE
PanelDue does not recognize SD card with RADDS

### ISSUE THREAD

**Issue by AbuShaqra** [dc42/PanelDue#13]
Hello, I've finally got the PanelDue to work with my RADDS board using repetier firmware.

but I am still facing a problem that the PanelDue shows that there is no SD card in both case when I use the RADDS onboard slot or the slot on the back of the TFT.

 I've got the 10p ribbon cable connected to the external SD pins and I checked all my wiring, no luck so far. any help would be highly appreciated

**Comment by dc42** [comment]
Hi,

1. Repetier does not yet fully support PanelDue. The Repetier devs have been working on this, also I am going to make some changes to PanelDue to make it easier for them. If you can't list the contents of the builtin card on PanelDue, then I guess they haven't implemented the M20 S2 command yet, which is what PanelDue needs for the file list to work.

2. The RADDS SD card pinout is different from the pinout used by Duet WiFi and other electronics, so a straight through 10-pin cable won't work with RADDS.

3. It's also possible to run RepRapFirmware on RADDS, with full PanelDue support.

**Comment by AbuShaqra** [comment]
Thank you for the quick reply David.

So can I say that if I get the wiring right and add support for the M20 S2 command I can get it to work?

I will give the RepRap Firmware  a try, it's just that I prefer using the repetier because I have previous experience with it.

**Comment by dc42** [comment]
There is one complication. Currently, RRF looks in folder /gcodes on the SD card for gcode files on the first SD card. It's occurred to me that perhaps Repetier does already support M20 S2, but you have no /gcodes folder so you don't see any files. One of the changes I am planning is that when the host includes "firmwareName":"Repetier" in the extended status response (see http://reprap.org/wiki/G-code#M408:_Report_JSON-style_response), it will look in the root folder instead.

**Comment by AbuShaqra** [comment]
All clear, can you give me a tip on which fork of RepRapFirmware I can use the best for RADDS board.

And if there is a complete documentation for how to flash and configure it. thank you

**Comment by AbuShaqra** [comment]
Alright, I tried flashing the "RepRapFirmware-RADDS-1.17c.bin" release and first I specified the port as COM3 where my board appeared in the device manager, I got this message; No device found on COM3.

this is the command I used: bossac.exe --port=COM3 -e -w -v -b "C:\Users\Abu Shaqra\Downloads\RepRapFirmware-RADDS-1.17c.bin"

I then used this command: bossac.exe -e -w -v -b "C:\Users\Abu Shaqra\Downloads\RepRapFirmware-RADDS-1.17c.bin"

and got this error:  Auto scan for device failed
                               Try specifying a serial port with the '-p' option

**Comment by dc42** [comment]
Press the Erase button on the Due. Then look in Device manager for which port is the "Bossa port". Then run bossac using that port.

**Comment by AbuShaqra** [comment]
thank you

**Comment by dc42** [comment]
Firmware development has been moved to the PanelDueFirmware repository. Please create a new issue in that repository if this is still a requirement.
