### ISSUE TITLE
'strcasecmp' not declared error

### ISSUE THREAD

**Issue by soosalameh** [dc42/PanelDue#15]
Hello,

I'm trying to compile the project and keep getting the error "'strcasecmp' was not declared in this scope"

As far as I know, the header files are referenced properly, and I can't figure out what the issue is.

Any ideas?

**Comment by dc42** [comment]
Are you using the code from the PanelDue repository and compiling it with Atmel Studio, or using the code from PanelDueFirmware and compiling with Eclipse?

**Comment by dc42** [comment]
This has been fixed,
