### ISSUE TITLE
main.c missing?

### ISSUE THREAD

**Issue by Kulitorum** [dc42/PanelDue#16]
I just downloaded Atmel Studio on windows 10 and opening the project file, PanelDue.cppproj I get nothing. - No source code, no main window. But also no error messages.

I opened the project file in a text editor, and the first line refers the file

common/applications/user_application/main.c

But theres no main.c in the whole project and no common folder.

Did I do something wrong?

Kulitorum

**Comment by dc42** [comment]
The source code is all in subdirectory /src.

However, I recently moved the PanelDue firmware to a new github repo called PanelDueFirmware and I now build it under Eclipse. You might want to start ftom that version.

**Comment by Kulitorum** [comment]
ok, thanks.

Can you please add compile instructions to PanelDueFirmware repo?
I installed Eclipse Neon 2, downloaded the repo and tried to compile it. Got 169 errors in Display.cpp alone.

Thank you

Kulitorum

**Comment by dc42** [comment]
Done.

**Comment by Kulitorum** [comment]
Thank you :)
