### ISSUE TITLE
My list of PanelDue Requests

### ISSUE THREAD

**Issue by Eddiiie** [dc42/PanelDue#18]
Unable to change temperature of heater1 when any tool besides 1 is selected, example touch tool 2 and set the temp, it will not work.  I have mixing extruder (diamond hotend) and have only 1 heater.   Works fine from webgui.
Add Z height to Print Status screen
Add Layer number to Print Status screen
Show which extruder/tool is active, or change the color so it is visible
Change font on exturder/tool buttons to make text readable
Display IP address somewhere, I forget it from time to time.
More color choices
Emergency Stop button

**Comment by dc42** [comment]
Please log new issues in the new repository PanelDueFirmware, not this one.
