### ISSUE TITLE
Adjusting Tool Flow Rate is Not Consistent With the Tool that the Change was Made to

### ISSUE THREAD

**Issue by bmalcheski** [dc42/PanelDue#19]
This is best described with pictures which I have uploaded.

In "Panel 1" I was attempting to adjust the flowrate of Tool 3 to 99%. But it appears that either the value is just displayed in the wrong spot or that the change is applied to the wrong tool.

I then tried to change Tool 3 to 100% and get the result in "Panel 2." Again, the adjustment being applied to the wrong tool or the new value displayed in the wrong position.

I then adjusted Tool 1 to 100% and got the result in "Panel 3." I noticed this bug while in the middle of a large print so I did not want to do too much messing around but could do some more trouble shooting if necessary.

Panel 1
![panel 1](https://user-images.githubusercontent.com/3670673/30121721-06c85d2e-92f2-11e7-9faa-7efeb1ccc6f6.jpg)

Panel 2
![panel 2](https://user-images.githubusercontent.com/3670673/30121722-06d15262-92f2-11e7-8cf5-9cf3d57d336f.jpg)

Panel 3
![panel 3](https://user-images.githubusercontent.com/3670673/30121723-06d39126-92f2-11e7-9f6a-b4c1a245157a.jpg)

**Comment by dc42** [comment]
This is believed fixed in the latest beta from the PanelDueFirmware repository. If you don't think it is fixed in that beta, please create a new issue in that repository.
