### ISSUE TITLE
PanelDue doesn't show folders beyond first page ...

### ISSUE THREAD

**Issue by dotorg** [dc42/PanelDue#20]
I'm having an issue that has made the PanelDue pretty much unusable for starting prints. The file listing seems to only support showing folder/directories on the first page. So anything more than eight, and there's no way to access them.

Strangely, too, I can't tell how its determining which eight to show. Its not the first or last alphabetically, and it doesn't seem to be date related, but it *is* consistent.

**Comment by dc42** [comment]
This repo is no longer maintained. Firmware development moved to the PanelDueFirmware repo a long time ago.

**Comment by dotorg** [comment]
Both up to date, and it doesn't work for me. Files are displayed fine in the web console. Folders are only displayed on the first page. Obviously I'd used the scroll buttons, otherwise I wouldn't know they don't show up on any of the other pages. 

Seems... bizarre... to just blindly close a bug that a paying customer reports just because you don't see it. "Well, we'll just ship your computer, then" is what I'd sarcastically say to any of the engineers in my organization who said that.  Should I just keep posting a new bug report until you accept there's something not working, or do you just not care something isn't?  If the latter is the case, I'll just fork and fix the bug myself. 

PanelDue 1.17
All the Duet firmwares are 1.20, although the problem existed prior to that. I didn't have that many folders prior to the upgrade to 1.17 on the PanelDue, so I can't speak to if it was a problem on prior versions.
Edit:
FWIW, looking at the code, I suspect the issue is not specifically directories not going beyond the first page, but the 2048 byte limit to the file list at FileManager.cpp:25, and its just a coincidence that eight directories happen to be in the file list prior to being truncated. The additional missing files aren't as obvious because I almost always work in subdirectories. 

I'll just rebuild it with a bigger vector, but if its really behaving as intended, it may be worth documenting that there's  2kb limit to the total length of all the filenames shown in a directory. I'd bet people are running into it and not realizing it.

**Comment by dc42** [comment]
I closed this report because it is in the wrong repository.

**Comment by dotorg** [comment]
Should I repost it in the other one, then, with more specifics about the
issue?

I hope you understand how closing it without saying that, and a blanket
statement that there's no problem is ... off putting.

**Comment by dc42** [comment]
Yes please.
