### ISSUE TITLE
[Discussion point] Axis positions should report commanded position.

### ISSUE THREAD

**Issue by T3P3** [dc42/PanelDue#4]
When using the display to command long moves, for example Z200 to Z50 using the -5mm button. I tend to press the button more time than required because the head is still moving, and the reported position takes time to update.

If the number displayed was immediately the commanded position (possibly with a background change to indicate the difference) this would prevent going past the commanded position.

Thoughts?

**Comment by dc42** [comment]
Firmware development has been moved to the PanelDueFirmware repository. Please create a new issue in that repository if this is still a requirement.
