### ISSUE TITLE
Inconsistent layer height display.

### ISSUE THREAD

**Issue by y00rek** [dc42/PanelDue#7]
I just noticed a slight inconsistency with layer height display. I DWC the layer height is displayed correctly as 0.25. PanelDue in print confirmation popup (the one that gets displayed when a file from SD card is selected for printing) displays it as 0.3. There must be some rounding going on here. It does not affect anything but just for the sake of being pedantic....

**Comment by dc42** [comment]
Thanks for your report. The layer height is currently displayed to only 1 decimal place. I will increase it to 2 in the next release.

**Comment by dc42** [comment]
Firmware development has been moved to the PanelDueFirmware repository. Please create a new issue in that repository if this is still a problem.
