### ISSUE TITLE
Feature Request: innocuous display of the Duet's IP address

### ISSUE THREAD

**Issue by dcnewman** [dc42/PanelDue#8]
Nice to be able to power up the printer and see right away on the Panel Due the IP address assigned to the underlying Duet or Duet WiFi.  Yes, it can be found by going to the console and manually entering a command, but might be nice to have it just there in small type somewhere on the main screen.

**Comment by dc42** [comment]
Firmware development has been moved to the PanelDueFirmware repository. Please create a new issue in that repository if this is still a requirement.
