### ISSUE TITLE
Incorrect layer fan percentage display

### ISSUE THREAD

**Issue by y00rek** [dc42/PanelDue#9]
The layer fan speed is not shown correctly. DWC shows it as 100% whereas PanelDue shows it as 1%
![img_5521](https://cloud.githubusercontent.com/assets/799238/16210927/dbbe2088-373e-11e6-8994-06ee708102d0.jpg)

**Comment by dc42** [comment]
Firmware development has been moved to the PanelDueFirmware repository. Please create a new issue in that repository if this is still a problem.
